// Registry of popular LLM providers with pre-filled configuration
export const LLM_PROVIDERS = [
  {
    id: 'openai',
    label: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    endpoint: '/chat/completions',
    model_id: 'gpt-4o-mini',
    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-3.5-turbo', 'o1', 'o1-mini', 'o3-mini'],
    max_tokens: 4096,
    color: 'text-emerald-600',
    bg: 'bg-emerald-50',
    border: 'border-emerald-200',
    free: false,
    docs: 'https://platform.openai.com/docs',
  },
  {
    id: 'anthropic',
    label: 'Anthropic (Claude)',
    baseUrl: 'https://api.anthropic.com/v1',
    endpoint: '/messages',
    model_id: 'claude-3-haiku-20240307',
    models: ['claude-opus-4-5', 'claude-sonnet-4-5', 'claude-3-5-haiku-latest', 'claude-3-haiku-20240307'],
    max_tokens: 4096,
    color: 'text-orange-600',
    bg: 'bg-orange-50',
    border: 'border-orange-200',
    free: false,
    docs: 'https://docs.anthropic.com',
  },
  {
    id: 'google',
    label: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    endpoint: '/models/gemini-1.5-flash:generateContent',
    model_id: 'gemini-1.5-flash',
    models: ['gemini-2.0-flash', 'gemini-1.5-flash', 'gemini-1.5-pro', 'gemini-2.5-pro-preview'],
    max_tokens: 8192,
    color: 'text-blue-600',
    bg: 'bg-blue-50',
    border: 'border-blue-200',
    free: true,
    docs: 'https://ai.google.dev/docs',
  },
  {
    id: 'groq',
    label: 'Groq (Gratuito)',
    baseUrl: 'https://api.groq.com/openai/v1',
    endpoint: '/chat/completions',
    model_id: 'llama-3.3-70b-versatile',
    models: ['llama-3.3-70b-versatile', 'llama3-8b-8192', 'mixtral-8x7b-32768', 'gemma2-9b-it', 'deepseek-r1-distill-llama-70b'],
    max_tokens: 8192,
    color: 'text-violet-600',
    bg: 'bg-violet-50',
    border: 'border-violet-200',
    free: true,
    docs: 'https://console.groq.com/docs',
  },
  {
    id: 'mistral',
    label: 'Mistral AI',
    baseUrl: 'https://api.mistral.ai/v1',
    endpoint: '/chat/completions',
    model_id: 'mistral-small-latest',
    models: ['mistral-large-latest', 'mistral-small-latest', 'mistral-nemo', 'codestral-latest', 'open-mistral-7b'],
    max_tokens: 4096,
    color: 'text-rose-600',
    bg: 'bg-rose-50',
    border: 'border-rose-200',
    free: false,
    docs: 'https://docs.mistral.ai',
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/v1',
    endpoint: '/chat/completions',
    model_id: 'deepseek-chat',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    max_tokens: 4096,
    color: 'text-cyan-600',
    bg: 'bg-cyan-50',
    border: 'border-cyan-200',
    free: false,
    docs: 'https://platform.deepseek.com/docs',
  },
  {
    id: 'perplexity',
    label: 'Perplexity AI',
    baseUrl: 'https://api.perplexity.ai',
    endpoint: '/chat/completions',
    model_id: 'llama-3.1-sonar-large-128k-online',
    models: ['llama-3.1-sonar-large-128k-online', 'llama-3.1-sonar-small-128k-online', 'llama-3.1-sonar-huge-128k-online'],
    max_tokens: 4096,
    color: 'text-teal-600',
    bg: 'bg-teal-50',
    border: 'border-teal-200',
    free: false,
    docs: 'https://docs.perplexity.ai',
  },
  {
    id: 'together',
    label: 'Together AI',
    baseUrl: 'https://api.together.xyz/v1',
    endpoint: '/chat/completions',
    model_id: 'meta-llama/Llama-3-70b-chat-hf',
    models: ['meta-llama/Llama-3-70b-chat-hf', 'mistralai/Mixtral-8x7B-Instruct-v0.1', 'Qwen/Qwen2-72B-Instruct', 'google/gemma-2-27b-it'],
    max_tokens: 4096,
    color: 'text-indigo-600',
    bg: 'bg-indigo-50',
    border: 'border-indigo-200',
    free: false,
    docs: 'https://docs.together.ai',
  },
  {
    id: 'cohere',
    label: 'Cohere',
    baseUrl: 'https://api.cohere.ai/v1',
    endpoint: '/chat',
    model_id: 'command-r-plus',
    models: ['command-r-plus', 'command-r', 'command', 'command-light'],
    max_tokens: 4096,
    color: 'text-pink-600',
    bg: 'bg-pink-50',
    border: 'border-pink-200',
    free: false,
    docs: 'https://docs.cohere.com',
  },
  {
    id: 'fireworks',
    label: 'Fireworks AI',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    endpoint: '/chat/completions',
    model_id: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    models: ['accounts/fireworks/models/llama-v3p1-70b-instruct', 'accounts/fireworks/models/mixtral-8x7b-instruct', 'accounts/fireworks/models/qwen2-72b-instruct'],
    max_tokens: 4096,
    color: 'text-amber-600',
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    free: false,
    docs: 'https://readme.fireworks.ai',
  },
  {
    id: 'openrouter',
    label: 'OpenRouter (Multi-modelo)',
    baseUrl: 'https://openrouter.ai/api/v1',
    endpoint: '/chat/completions',
    model_id: 'openai/gpt-4o-mini',
    models: ['openai/gpt-4o', 'openai/gpt-4o-mini', 'anthropic/claude-3.5-sonnet', 'google/gemini-flash-1.5', 'meta-llama/llama-3.1-70b-instruct:free', 'mistralai/mistral-7b-instruct:free'],
    max_tokens: 4096,
    color: 'text-slate-600',
    bg: 'bg-slate-50',
    border: 'border-slate-200',
    free: true,
    docs: 'https://openrouter.ai/docs',
  },
  {
    id: 'huggingface',
    label: 'Hugging Face Inference',
    baseUrl: 'https://api-inference.huggingface.co/v1',
    endpoint: '/chat/completions',
    model_id: 'meta-llama/Llama-3.1-8B-Instruct',
    models: ['meta-llama/Llama-3.1-8B-Instruct', 'mistralai/Mistral-7B-Instruct-v0.3', 'Qwen/Qwen2.5-72B-Instruct', 'microsoft/Phi-3.5-mini-instruct'],
    max_tokens: 2048,
    color: 'text-yellow-600',
    bg: 'bg-yellow-50',
    border: 'border-yellow-200',
    free: true,
    docs: 'https://huggingface.co/docs/api-inference',
  },
  {
    id: 'ollama',
    label: 'Ollama (Local)',
    baseUrl: 'http://localhost:11434/v1',
    endpoint: '/chat/completions',
    model_id: 'llama3.2',
    models: ['llama3.2', 'llama3.1', 'mistral', 'gemma2', 'phi3', 'qwen2.5', 'deepseek-r1', 'codellama'],
    max_tokens: 4096,
    color: 'text-gray-600',
    bg: 'bg-gray-50',
    border: 'border-gray-200',
    free: true,
    docs: 'https://ollama.com/docs',
  },
  {
    id: 'xai',
    label: 'xAI (Grok)',
    baseUrl: 'https://api.x.ai/v1',
    endpoint: '/chat/completions',
    model_id: 'grok-beta',
    models: ['grok-beta', 'grok-vision-beta', 'grok-2'],
    max_tokens: 4096,
    color: 'text-neutral-600',
    bg: 'bg-neutral-50',
    border: 'border-neutral-200',
    free: false,
    docs: 'https://docs.x.ai',
  },
  {
    id: 'nvidia',
    label: 'NVIDIA NIM',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    endpoint: '/chat/completions',
    model_id: 'meta/llama-3.1-70b-instruct',
    models: ['meta/llama-3.1-70b-instruct', 'nvidia/llama-3.1-nemotron-70b-instruct', 'mistralai/mixtral-8x7b-instruct-v0.1', 'google/gemma-2-27b-it'],
    max_tokens: 4096,
    color: 'text-green-700',
    bg: 'bg-green-50',
    border: 'border-green-200',
    free: true,
    docs: 'https://docs.api.nvidia.com',
  },
  {
    id: 'custom',
    label: 'Personalizado (OpenAI-compatible)',
    baseUrl: '',
    endpoint: '/chat/completions',
    model_id: '',
    models: [],
    max_tokens: 2048,
    color: 'text-purple-600',
    bg: 'bg-purple-50',
    border: 'border-purple-200',
    free: null,
    docs: '',
  },
];